# Generated by Django 4.0.1 on 2022-01-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_investorinfo_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupinfo',
            name='business_model',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('C2B', 'C2B'), ('C2C', 'C2C')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startupinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='startupinfo',
            name='team_member1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='startupinfo',
            name='team_member2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='startupinfo',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='startupinfo',
            name='weblink',
            field=models.URLField(blank=True),
        ),
    ]
