# Generated by Django 4.0.1 on 2022-01-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_startupinfo_business_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorinfo',
            name='weblink',
            field=models.URLField(blank=True),
        ),
    ]
