# Generated by Django 4.0.1 on 2022-01-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_investorinfo_weblink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='looking_at',
            field=models.CharField(blank=True, choices=[('Finding Investees', 'Finding Investees'), ('Partnerships with Corporates', 'Partnerships with Corporates'), ('Partnerships with Startups', 'Partnerships with Startups'), ('Finding Investors', 'Finding Investors'), ('Finding Mentors', 'Finding Mentors')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startupinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investorinfo',
            name='weblink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
