# Generated by Django 4.0.1 on 2022-01-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customerinfo_biography_customerinfo_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorinfo',
            old_name='selected_role_image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='investorinfo',
            old_name='select_role1',
            new_name='person1',
        ),
        migrations.RenameField(
            model_name='investorinfo',
            old_name='select_role2',
            new_name='person2',
        ),
        migrations.RemoveField(
            model_name='investorinfo',
            name='selected_role_image2',
        ),
        migrations.RemoveField(
            model_name='investorinfo',
            name='selected_role_name1',
        ),
        migrations.RemoveField(
            model_name='investorinfo',
            name='selected_role_name2',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investorinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
