# Generated by Django 4.0.1 on 2022-01-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customerinfo_looking_at_customerinfo_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='looking_at',
            field=models.CharField(blank=True, choices=[('Finding Investees', 'Finding Investees'), ('Partnerships with Corporates', 'Partnerships with Corporates'), ('Partnerships with Startups', 'Partnerships with Startups'), ('Finding Investors', 'Finding Investors'), ('Finding Mentors', 'Finding Mentors'), ('others', 'others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investorinfo',
            name='looking_at',
            field=models.CharField(blank=True, choices=[('Finding Investees', 'Finding Investees'), ('Partnerships with Corporates', 'Partnerships with Corporates'), ('Partnerships with Startups', 'Partnerships with Startups'), ('Finding Investors', 'Finding Investors'), ('Finding Mentors', 'Finding Mentors'), ('others', 'others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startupinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='startupinfo',
            name='sector',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('Robotics', 'Robotics'), ('Data Analysis', 'Data Analysis'), ('Biotech', 'Biotech'), ('Agritech', 'Agritech'), ('Bigdata', 'Bigdata'), ('Blockchain', 'Blockchain'), ('cybersecurity', 'cybersecurity'), ('Digital Health', 'Digital Health'), ('Education', 'Education'), ('E-commerce', 'E-commerce'), ('Entertainments', 'Entertainments'), ('Events', 'Events'), ('Food&Beverage', 'Food&Beverage'), ('Fintech', 'Fintech'), ('Food Science & Technology', 'Food Science & Technology'), ('Gaming', 'Gaming'), ('Hardware', 'Hardware'), ('Healthcare', 'Healthcare'), ('Infotech', 'Inftech'), ('IOT', 'IOT'), ('Manufacturing & Engineering', 'Manufacturing & Engineering'), ('Media', 'Media'), ('Nanotechnology', 'Nanotechnology'), ('Pharmaceutical', 'Pharmaceutical'), ('Real Estate', 'Real Estate'), ('Telecom', 'Telecom'), ('Trasport', 'Transport'), ('Travel & Hospitality', 'Travel & Hospitality'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
