# Generated by Django 4.0.1 on 2022-01-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customerinfo_looking_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
