# Generated by Django 4.0.1 on 2022-01-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_startupinfo_looking_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupinfo',
            old_name='team_member1',
            new_name='selected_role_image1',
        ),
        migrations.RenameField(
            model_name='startupinfo',
            old_name='team_member2',
            new_name='selected_role_image2',
        ),
        migrations.AddField(
            model_name='startupinfo',
            name='select_role1',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Founder', 'Founder'), ('CEO & Founder', 'CEO & Founder'), ('Co-Founder', 'Co-Founder'), ('Manager', 'Manager')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startupinfo',
            name='select_role2',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Founder', 'Founder'), ('CEO & Founder', 'CEO & Founder'), ('Co-Founder', 'Co-Founder'), ('Manager', 'Manager')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startupinfo',
            name='selected_role_name1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupinfo',
            name='selected_role_name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startupinfo',
            name='videofile',
            field=models.FileField(blank=True, default='Not availabe', null=True, upload_to='videos/'),
        ),
    ]
