# Generated by Django 4.0.1 on 2022-02-10 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_threadmodel_notification_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='sector',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('Agritech', 'Agritech'), ('Robotics', 'Robotics'), ('Data Analysis', 'Data Analysis'), ('Biotech', 'Biotech'), ('Bigdata', 'Bigdata'), ('Blockchain', 'Blockchain'), ('cybersecurity', 'cybersecurity'), ('Digital Health', 'Digital Health'), ('Education', 'Education'), ('E-commerce', 'E-commerce'), ('Entertainments', 'Entertainments'), ('Events', 'Events'), ('Food&Beverage', 'Food&Beverage'), ('Fintech', 'Fintech'), ('Food Science & Technology', 'Food Science & Technology'), ('Gaming', 'Gaming'), ('Hardware', 'Hardware'), ('Healthcare', 'Healthcare'), ('Infotech', 'Inftech'), ('IOT', 'IOT'), ('Manufacturing & Engineering', 'Manufacturing & Engineering'), ('Media', 'Media'), ('Nanotechnology', 'Nanotechnology'), ('Pharmaceutical', 'Pharmaceutical'), ('Real Estate', 'Real Estate'), ('Telecom', 'Telecom'), ('Trasport', 'Transport'), ('Travel & Hospitality', 'Travel & Hospitality'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investorinfo',
            name='tags',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('Agritech', 'Agritech'), ('Robotics', 'Robotics'), ('Data Analysis', 'Data Analysis'), ('Biotech', 'Biotech'), ('Bigdata', 'Bigdata'), ('Blockchain', 'Blockchain'), ('cybersecurity', 'cybersecurity'), ('Digital Health', 'Digital Health'), ('Education', 'Education'), ('E-commerce', 'E-commerce'), ('Entertainments', 'Entertainments'), ('Events', 'Events'), ('Food&Beverage', 'Food&Beverage'), ('Fintech', 'Fintech'), ('Food Science & Technology', 'Food Science & Technology'), ('Gaming', 'Gaming'), ('Hardware', 'Hardware'), ('Healthcare', 'Healthcare'), ('Infotech', 'Inftech'), ('IOT', 'IOT'), ('Manufacturing & Engineering', 'Manufacturing & Engineering'), ('Media', 'Media'), ('Nanotechnology', 'Nanotechnology'), ('Pharmaceutical', 'Pharmaceutical'), ('Real Estate', 'Real Estate'), ('Telecom', 'Telecom'), ('Trasport', 'Transport'), ('Travel & Hospitality', 'Travel & Hospitality'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startupinfo',
            name='sector',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('Agritech', 'Agritech'), ('Robotics', 'Robotics'), ('Data Analysis', 'Data Analysis'), ('Biotech', 'Biotech'), ('Bigdata', 'Bigdata'), ('Blockchain', 'Blockchain'), ('cybersecurity', 'cybersecurity'), ('Digital Health', 'Digital Health'), ('Education', 'Education'), ('E-commerce', 'E-commerce'), ('Entertainments', 'Entertainments'), ('Events', 'Events'), ('Food&Beverage', 'Food&Beverage'), ('Fintech', 'Fintech'), ('Food Science & Technology', 'Food Science & Technology'), ('Gaming', 'Gaming'), ('Hardware', 'Hardware'), ('Healthcare', 'Healthcare'), ('Infotech', 'Inftech'), ('IOT', 'IOT'), ('Manufacturing & Engineering', 'Manufacturing & Engineering'), ('Media', 'Media'), ('Nanotechnology', 'Nanotechnology'), ('Pharmaceutical', 'Pharmaceutical'), ('Real Estate', 'Real Estate'), ('Telecom', 'Telecom'), ('Trasport', 'Transport'), ('Travel & Hospitality', 'Travel & Hospitality'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
