# Generated by Django 4.0.1 on 2022-02-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_friends_alter_customerinfo_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.threadmodel'),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
