# Generated by Django 4.0.1 on 2022-01-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_team_member1_startupinfo_selected_role_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorinfo',
            old_name='team_member1',
            new_name='selected_role_image1',
        ),
        migrations.RenameField(
            model_name='investorinfo',
            old_name='team_member2',
            new_name='selected_role_image2',
        ),
        migrations.AddField(
            model_name='investorinfo',
            name='select_role1',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Founder', 'Founder'), ('CEO & Founder', 'CEO & Founder'), ('Co-Founder', 'Co-Founder'), ('Manager', 'Manager')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investorinfo',
            name='select_role2',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Founder', 'Founder'), ('CEO & Founder', 'CEO & Founder'), ('Co-Founder', 'Co-Founder'), ('Manager', 'Manager')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investorinfo',
            name='selected_role_name1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investorinfo',
            name='selected_role_name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investorinfo',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('Angel Investor', 'Angel Investor'), ('Peer to peer Lenders', 'peer to peer Lenders'), ('Personal Investors', 'Personal Investors'), ('Bank', 'Bank'), ('Venture Capitalists', 'Venture Capitalists')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investorinfo',
            name='tags',
            field=models.CharField(blank=True, choices=[('AI', 'AI'), ('Robotics', 'Robotics'), ('Data Analysis', 'Data Analysis'), ('Biotech', 'Biotech'), ('Agritech', 'Agritech'), ('Bigdata', 'Bigdata'), ('Blockchain', 'Blockchain'), ('cybersecurity', 'cybersecurity'), ('Digital Health', 'Digital Health'), ('Education', 'Education'), ('E-commerce', 'E-commerce'), ('Entertainments', 'Entertainments'), ('Events', 'Events'), ('Food&Beverage', 'Food&Beverage'), ('Fintech', 'Fintech'), ('Food Science & Technology', 'Food Science & Technology'), ('Gaming', 'Gaming'), ('Hardware', 'Hardware'), ('Healthcare', 'Healthcare'), ('Infotech', 'Inftech'), ('IOT', 'IOT'), ('Manufacturing & Engineering', 'Manufacturing & Engineering'), ('Media', 'Media'), ('Nanotechnology', 'Nanotechnology'), ('Pharmaceutical', 'Pharmaceutical'), ('Real Estate', 'Real Estate'), ('Telecom', 'Telecom'), ('Trasport', 'Transport'), ('Travel & Hospitality', 'Travel & Hospitality'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
