# Generated by Django 4.0.1 on 2022-01-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_team_member1_investorinfo_selected_role_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
