# Generated by Django 4.0.1 on 2022-02-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_investorinfo_thread_startupinfo_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorinfo',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='startupinfo',
            name='thread',
        ),
    ]
