# Generated by Django 4.0.1 on 2022-02-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_investorinfo_thread_remove_startupinfo_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='image',
            field=models.ImageField(blank=True, default='images/images.png', null=True, upload_to='images/'),
        ),
    ]
