# Generated by Django 4.0.1 on 2022-02-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customerinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
