# Generated by Django 4.0.1 on 2022-03-02 14:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_customerinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupinfo',
            name='market_presence',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Khulna', 'khulna'), ('Barishal', 'Barishal'), ('Rajsahi', 'Rajsahi'), ('Chittagong', 'Chittagong'), ('Shylet', 'Shylet'), ('Rangpur', 'Rangpur'), ('Mymensing', 'Mymensing')], max_length=65, null=True),
        ),
    ]
