# Generated by Django 4.0.1 on 2022-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_startupinfo_market_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupinfo',
            name='market_presence',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Khulna', 'khulna'), ('Barishal', 'Barishal'), ('Rajsahi', 'Rajsahi'), ('Chittagong', 'Chittagong'), ('Shylet', 'Shylet'), ('Rangpur', 'Rangpur'), ('Mymensing', 'Mymensing')], max_length=100, null=True),
        ),
    ]
