# Generated by Django 4.2.1 on 2023-08-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_notification_message_notification_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
